### ISSUE TITLE
Project landing page

### ISSUE THREAD

**Issue by psforscher** [rempsyc/busara_dashboard#1]
The dashboard needs a landing page that explains the context and motivation of the project and the criteria used for some of our decisions (eg the selection of journals). We could also consider adding a big-picture takeaway on this page & a call to action

More info here: https://docs.google.com/document/d/1e_cf1M1vUAzeyKCq77ClJPa5cDB-XAk60bI0cCKUOzw/edit

**Comment by psforscher** [comment]
Some thoughts from Chuan-Peng:

The criteria for including a journal is not clear to me. I think there are many similar journals that are not included, e.g., in developing psych, Child Development, Developmental Science are good journals too, in social psych, PSPB is also regarded as a good journal. I guess it's better to have a clearer criteria for inclusion.

**Comment by rempsyc** [comment]
The dashboard's landing page now starts with the big-picture takeaway at the top and centered, along with three columns on the second row.
- The first column explains the context and motivation of the project as well as a call to action
- The second column explains the criteria used for the selection of journals
- The third colum includes information about me and the Busara Center

Furthermore, the website now:
- displays a browser icon (#8)
- organizes the different pages with dropdown menus (#6)
- links back to the home page when clicking on the dashboard title at the top left now (#7)

**Comment by psforscher** [comment]
This is great, and a huge improvement! I have a couple comments:

- Might it be possible to say "behavioral science" instead of "behavioral science and psychology"? I am thinking of behavioral science as the interdisciplinary field that draws on both economics and psychology (hence the reason to audit economics and psychology journals)
- To that end, perhaps the "journal selection" section can say that the journals were chosen to broadly represent the interdisciplinary field of behavioral science and the fields that contribute to it (economics and psychology), and were selected by soliciting input from colleagues
- Change "Representativity" to "Representativeness"
- Under "About the authors", my current title is "Director", rather than "Research Lead"

**Comment by rempsyc** [comment]
For your bio, what I had from your email signature was
> Director, Meta-Research Team
Culture, Research Ethics, MEthods (CREME)

And the dashboard currently reads as:
> He is currently the Research Lead at the Busara Center for Behavioral Economics, in Kenya, **where he also leads** the Culture, Research Ethics, and MEthods (CREME) project **as director of the Meta-Research Team.**

So I was already saying that you are director of the Meta-Research Team, but I don't just want to replace Research Lead for Director, because then we would get:
> He is currently the Director at the Busara Center for Behavioral Economics

So could you provide a corrected bio that is more in line with what you had in mind? E.g.,

> **[Patrick Forscher](https://busaracenter.org/patrick-s-forscher/)** is the primary collaborator on this project. He is currently the Director of the Meta-Research Team where he leads the Culture, Research Ethics, and MEthods (CREME) project at the Busara Center for Behavioral Economics, in Kenya. The dashboard was Patrick's original vision, and frequently benefits from his creative input.

**Comment by rempsyc** [comment]
Once we fix this I think we can close this issue and check point 1 in #33

**Comment by psforscher** [comment]
> [Patrick Forscher](https://busaracenter.org/patrick-s-forscher/) is the primary collaborator on this project. He is currently the Director of the Culture, Research Ethics, and MEthods (CREME) Meta-Research Team at the Busara Center for Behavioral Economics. The dashboard was Patrick's original vision, and frequently benefits from his creative input.
