### ISSUE TITLE
Reorganize navigation menu?

### ISSUE THREAD

**Issue by rempsyc** [rempsyc/busara_dashboard#14]
Right now, we have the following structure: 

<img width="652" alt="image" src="https://github.com/rempsyc/busara_dashboard/assets/13123390/c7615c79-b95d-4a7b-8d29-e28516ebd9f6">

Where all Continent visualizations are collapsed together, and all Country visualizations together, and then a subtab for field-specific visualizations which are only the main one.

One possibility would be to change the organization to have fields as dropdowns, so:
- One "All Fields" dropdown, with six options (all the continents + all the countries)
- One "Psychology" dropdown, also with the full six options
- One "Economics" dropdown, also with the full six options
- One "General" dropdown, also with the full six options

Then we could really better compare each graph by field. Thoughts?

**Comment by psforscher** [comment]
I like this idea.

I'd also put "Methods" just to the left of "Limitations". Also, is "Figure 1" necessary anymore?
