### ISSUE TITLE
Journal names not visible in waffle plot

### ISSUE THREAD

**Issue by rempsyc** [rempsyc/busara_dashboard#20]
One reviewer commented,

> Before getting to your questions, just one small issue, see the screenshot below (journal names are not fully visible). 

To address this issue, I have changed to using the journal name **abbreviations** per default. However, even some abbreviations are still very long, so I suppose this does not fully address the issue, but I'm not sure what else we could easily do.

**Comment by psforscher** [comment]
Abbreviations are a good temporary solution, but I suspect that the bigger solution will involve solving issue #29
