### ISSUE TITLE
Problem with PSPB

### ISSUE THREAD

**Issue by rempsyc** [rempsyc/busara_dashboard#28]
I've been having problems with PSPB for a while now... linked to #26.

The issue is that internally on PubMed, PSPB is written with an Ampersand. It seems that when I search with "and" instead of "&", PubMed provides no results. Yet, when I include "&", then it creates a bug when retrieving data. I've been doing a lot of back and forth on this, with no resolution so far.

<img width="566" alt="image" src="https://github.com/rempsyc/busara_dashboard/assets/13123390/00a0aa65-dd98-42f8-844a-2dc1dbdfadbe">

---

<img width="561" alt="image" src="https://github.com/rempsyc/busara_dashboard/assets/13123390/6abe6fe0-cf61-447c-b1cf-585fb8a4d034">

---
Trying with "and" instead of "&"

<img width="467" alt="image" src="https://github.com/rempsyc/busara_dashboard/assets/13123390/9ea66801-6648-4069-a24e-180091a196b1">

---

Trying with "&" also doesn't work (time out because too many results somehow, but that shouldn't be the case)

<img width="444" alt="image" src="https://github.com/rempsyc/busara_dashboard/assets/13123390/d7fe6a04-d4de-472a-898a-403392dd4c25">

---

The way it's internally saved by easyPubMed is `"Personality &amp; Social Psychology Bulletin"`, so I tried also using `&amp;` instead of `&`:

<img width="467" alt="image" src="https://github.com/rempsyc/busara_dashboard/assets/13123390/e2a4554e-abed-45a8-a2f1-d24bbd747238">

**Comment by rempsyc** [comment]
Using truncation with quotes is [not a solution](https://expertsearching.wordpress.com/2016/11/07/phrase-searching-in-pubmed-is-weirdly-complicated/)...

> **When search terms are in quotation marks, PubMed ignores the truncation symbol.** My strategy had relied heavily on truncated phrases, all of which were in quotation marks (to avoid PubMed’s automatic term mapping), and all of which were being interpreted as singular rather than plural terms (e.g. “patient outcome*” would search only for “patient outcome” and not “patient outcomes”).

**Comment by psforscher** [comment]
This is a bit of a shot in the dark, but could this be a character encoding issue? That has come up for some "big team" projects I've done with the Psychological Science Accelerator, where characters do not render correctly, leading to problems with study execution and/or data analysis.
