### ISSUE TITLE
Intimidating tables

### ISSUE THREAD

**Issue by psforscher** [rempsyc/busara_dashboard#3]
The tables were rather intimidating and could start collapsed, and/or we could better signpost the purpose of these (for people to have the exact statistics if they want these)

More info here: https://docs.google.com/document/d/1e_cf1M1vUAzeyKCq77ClJPa5cDB-XAk60bI0cCKUOzw/edit

**Comment by rempsyc** [comment]
Data pages now use tabs, with the default tab being the figure, meaning that tables sort of start collapsed, and an action is required to see them, without getting rid of them entirely.
