### ISSUE TITLE
Decide on final dashboard URL

### ISSUE THREAD

**Issue by rempsyc** [rempsyc/busara_dashboard#32]
Patrick noted,
> For the URL, I rather liked our CEO's, Chaning's, idea to call this the "Missing Majority" dashboard. [...] For now, let's keep the name "busara" at the end of the URL and change to a different one once we finalize the name.

But now that we have settled on "The Missing Majority Dashboard" (#13), I think we could change the URL from:

https://remi-theriault.com/dashboards/busara

to

https://remi-theriault.com/dashboards/missing_majority

WDYT @psforscher

I'm saying this because we'll need to cite the dashboard in Sakshi's paper so I'd prefer to use our final URL.

**Comment by psforscher** [comment]
makes sense to me!
