### ISSUE TITLE
Use a minimum number of papers per journal to be included

### ISSUE THREAD

**Issue by rempsyc** [rempsyc/busara_dashboard#37]
Consider using a minimum number of papers to be included in the tables and figures for quality guarantees. Specific criteria for exclusion should be discussed and agreed on. Related to data quality point 3 in #33

**Comment by rempsyc** [comment]
I wonder what the minimum number of papers should be. 100? We have to remember that this is over a 37-year period, meaning only 2.7 papers per year. Is this meaningful at all? Even then, this would result in excluding 21 journals, including 19 economics journals, i.e., most of them, since we have only 4 econ journals with > 100 (and not much more anyway).

**Comment by rempsyc** [comment]
@psforscher what would you recommend using for minimum number of papers per journal to be included on the dashboard? (see above reflections)

**Comment by psforscher** [comment]
for SIPS let's go with 50, but i think this issue might be resolved once we upgrade the database in issue #34
