### ISSUE TITLE
Add visual indicator for low sample-sized journals

### ISSUE THREAD

**Issue by rempsyc** [rempsyc/busara_dashboard#38]
Consider adding a small note on graphs about sample size for each journal indicative of data quality, e.g., more or less transparency for those that have lots or less data, dot sizes, etc. Related to point 3 in #33

**Comment by rempsyc** [comment]
@psforscher is it redundant to visually flag low sample-sized journals if we end up excluding them anyway in #37? I suppose we have to choose one or the other?

**Comment by psforscher** [comment]
i think this whole issue might be superseded by moving to `openAlexR` #34
