### ISSUE TITLE
Fix missing continents / group labels in waffle plots

### ISSUE THREAD

**Issue by rempsyc** [rempsyc/busara_dashboard#39]
Patrick noted in #31,
> There are a couple miscellaneous graphical issues that I noticed. [...] Africa missing on the Continent, by Journal plot. See below

<img width="651" alt="Screenshot 2024-03-18 at 00 26 57" src="https://github.com/rempsyc/busara_dashboard/assets/149572347/0688a487-5678-409b-9ad3-3774d83b85e1">

I answered,
> The missing continent for waffle plots I believe is a known issue with waffle plots for categories with little data. That said, it would be worth a more torough investigation again to document this behaviour properly.

We could try to fix this issue here.

**Comment by rempsyc** [comment]
The reason for this bug is that waffle plots show each square as = 1%, but Africa here represents less than 1%, and that squares that represent less than 1% are not shown. It seems the post below suggest some fixes that could be explored to clean this:

https://stackoverflow.com/questions/64607021/waffle-plot-does-not-show-one-group

**Comment by rempsyc** [comment]
@psforscher since the issue is due to continents or countries having less than 1% representation, one possible fix is to replace any value smaller than 1% to exactly 1% so that it shows both on the plot and on the legend. One issue that would bring is that the total would not amount to 100% anymore (it would be slightly greater) and that it would overestimate representation, e.g., something like 0.0001% would still be interpreted as 1% by the public. What do you recommend then here? It's not possible to have 0.0001% of a square, but another option would be to add the continents manually on the legend but not on the plot (so there still be empty squares and no squares representing Africa for example)

**Comment by psforscher** [comment]
i think i would favor adding countries manually on the legend and not the plot

**Comment by rempsyc** [comment]
Alas, the provided solutions are not working for our use case. I have opened a question on [Stackoverflow](https://stackoverflow.com/questions/78497245/how-to-show-groups-with-values-1-on-waffle-chart-legend) and it received a response, but it is rather unsatisfactory. So I have submitted a feature request to the package developer on GitHub (hrbrmstr/waffle#99).
