### ISSUE TITLE
Fix font and colour across the dashboard

### ISSUE THREAD

**Issue by rempsyc** [rempsyc/busara_dashboard#44]
Continuation of #41

> I believe that the fonts in the header/menu are different than those in the body of the dashboard. And the color of the header doesn’t match the title.

**Comment by rempsyc** [comment]
1. They are actually verified to all be the same font: Source Sans Pro

![image](https://github.com/rempsyc/busara_dashboard/assets/13123390/ba2ef690-4a1a-45f1-8662-1db1ed68d00c)

The take-home message is just also bold, and yes, a different colour because I thought it didn't look good to have it the same colour as the header

**Comment by rempsyc** [comment]
This is what it looks like when using the same font for the take-home message than the menu

![image](https://github.com/rempsyc/busara_dashboard/assets/13123390/e413e2ec-5240-45e3-a83b-e1afe928b61d)

The take-home message seem to appear as much darker... is it an illusion? It is! (Pallet colour detector gives the same code for both, #2780E3)

![image](https://github.com/rempsyc/busara_dashboard/assets/13123390/43704812-6b06-458d-9008-50ea18eb0271)

**Comment by rempsyc** [comment]
I think I prefer the old colour better for the take-home message (the new blue is a bit too aggressive I think). One option would be to change the colour of the menu to the greenish one, but I'm not sure it would look good.

**Comment by rempsyc** [comment]
Changing the colour of the whole dashboard to match the current take-home message colour, we would get this:

![image](https://github.com/rempsyc/busara_dashboard/assets/13123390/f6cda244-54fd-46b1-824d-5cb48d34e90f)

**Comment by rempsyc** [comment]
Any preference?

**Comment by psforscher** [comment]
i like the matching darker blue color
