### ISSUE TITLE
Bug: Some continents show 0% on scatter plot

### ISSUE THREAD

**Issue by rempsyc** [rempsyc/busara_dashboard#47]
the improvements make a huge difference! just a couple comments on this version:

- the over-time tables and graphs look like they must be drawing on different versions of the data. for example, compare the graphs and tables below; in 2024 in the table, Africa is listed at 4.78%, but in the graph that percentage is 0

<img width="1020" alt="Screenshot 2024-05-20 at 14 39 01" src="https://github.com/rempsyc/busara_dashboard/assets/149572347/04aa4f15-b80c-4b7e-b8dc-8a43be7b5a30">

<img width="1020" alt="Screenshot 2024-05-20 at 14 41 14" src="https://github.com/rempsyc/busara_dashboard/assets/149572347/8ac8182b-77ad-4760-92f1-27322efd6608">

- there's a similar inconsistency between the graphical data and the data listed in the waffle plots (compare the over-time graph to the waffle plot below; Africa is listed as contributing 2% of data in the waffle plot, but in the over-time graph, there is no time-point where it has above 0% of the data)
<img width="871" alt="Screenshot 2024-05-20 at 14 44 39" src="https://github.com/rempsyc/busara_dashboard/assets/149572347/e25ab042-54ef-4b3c-9b50-6f8ba5c3673e">

_Originally posted by @psforscher in https://github.com/rempsyc/busara_dashboard/issues/33#issuecomment-2120392742_

**Comment by rempsyc** [comment]
The waffle plot was correct and tables were correct, but the scatter plot for continents had a computation problem which has now been resolved. Thanks for reporting!

**Comment by rempsyc** [comment]
@psforscher in the end I detected some more discrepancies between the tables and waffle plots, and I have now fixed them. Imagine if we had removed the table in the beginning like some reviewers requested, fortunately we still have this data quality check 😅

Now though we have too many countries showing up (below)

<img width="610" alt="image" src="https://github.com/rempsyc/busara_dashboard/assets/13123390/250db2c5-3a82-4acf-ab34-ce0149168c31">

Waffle plots are not made to be visualized with more than 6 or so groupings. So what I did is I only pick the first five countries and stacked all the rest in "Other". I hope that's fine.

I remembered that you were saying that the scatter plots by countries were also overwhelming because of the number of countries (and also colours). So I wonder if a similar strategy would be viable here. What if we only kept the first six or so countries in the scatter plot and merged the rest of the data as "other"? I'm not so sure about it but just sharing the thought with you while it is fresh.

**Comment by psforscher** [comment]
yes, i think adding "Other" makes sense, and i like the idea of doing this in the scatterplot too -- as long as the table still shows all countries, so that the data are accessible to those who want to know.

**Comment by rempsyc** [comment]
Ok. Then what's a meaningful number for the scatter plot? Top 6? Top 10?

**Comment by psforscher** [comment]
let's say top 10

**Comment by rempsyc** [comment]
With this change the scrolling bar disappears and the corresponding instructions are now obsolete 😅
