### ISSUE TITLE
Filter general journal for behavioural science-related keywords

### ISSUE THREAD

**Issue by rempsyc** [rempsyc/busara_dashboard#48]
One issue I have also is that I fear behavioural science only represents a fraction of all Nature, Science, PNAS, and PloS One papers, so I don't know if we can legitimately use these data to make claims about behavioural science as a whole since because of their volume, these general journals overwhelm the rest of the data by a factor of 5, so the "All fields" page and gauges are misleading.

That said, the data provided by OpenAlex includes some topics tags, e.g.,

``` r
> (data %>% 
+   filter(id == "https://openalex.org/W2055287564") %>% 
+   pull(concepts))[[1]]
                                 id                               wikidata             display_name level     score
1   https://openalex.org/C122980154  https://www.wikidata.org/wiki/Q205555                  Feeling     2 0.6483988
2   https://openalex.org/C118563197  https://www.wikidata.org/wiki/Q185030                   Genius     2 0.6240414
3    https://openalex.org/C15744967    https://www.wikidata.org/wiki/Q9418               Psychology     0 0.5501474
4  https://openalex.org/C2780583480 https://www.wikidata.org/wiki/Q1366327        Tone (literature)     2 0.5363786
5   https://openalex.org/C146902061  https://www.wikidata.org/wiki/Q476590         Music psychology     3 0.5164297
6    https://openalex.org/C13553968   https://www.wikidata.org/wiki/Q27908          Music education     2 0.4173431
7   https://openalex.org/C107038049   https://www.wikidata.org/wiki/Q35986               Aesthetics     1 0.4106070
8   https://openalex.org/C153349607   https://www.wikidata.org/wiki/Q36649              Visual arts     1 0.3683655
9   https://openalex.org/C180747234   https://www.wikidata.org/wiki/Q23373     Cognitive psychology     1 0.3277530
10  https://openalex.org/C142362112     https://www.wikidata.org/wiki/Q735                      Art     0 0.2974586
11  https://openalex.org/C124952713    https://www.wikidata.org/wiki/Q8242               Literature     1 0.1627391
12   https://openalex.org/C77805123  https://www.wikidata.org/wiki/Q161272        Social psychology     1 0.1458697
13  https://openalex.org/C138496976  https://www.wikidata.org/wiki/Q175002 Developmental psychology     1 0.1236818
```

Perhaps it would be possible to filter all the general journal data for behavioural science-related tags? Again, I'm not sure if this is realistic in time for SIPS, but something to think about for the future... Or is it useful to have "all fields" as a _reference_ to compare psych and econ to? But then that shouldn't represent the aggregate data from the home page where we discuss the global south?

_Originally posted by @rempsyc in https://github.com/rempsyc/busara_dashboard/issues/33#issuecomment-2120506144_

**Comment by rempsyc** [comment]
@psforscher we can move the discussion here from #33. I just wrote some code to extract the concept tags in a usable format and I _could_ try to filter the general journals for the behavioural science keywords before SIPS, if you think it would be interesting / worth. However, this brings up two more questions:

1. Filtering is easy enough, but then we would need to decide on which keywords matter. Would simply using `"psych*"` and `"econ*"` be sufficient for the short term? I feel like this decision will inherently be subjective and necessarily lets some other concepts behind. There are also conceptual problems, even with the psychology tag, these journals frequently have "neuropsychology", but does that fall within behavioural science? I'd think not but that's the kind of subjective decision we would need to take and that complicates the filtering process (include psychology, but not if it also includes the word "neuro"?).
2. A second question is how to communicate this information in the dashboard. Doing this sort of data filtering complicates the easy communication of what the data means considerably. People understand that the data represent a specific journal, but then saying that some journals depend on specific keywords complexifies things quickly.
3. Is this too rushed of a decision for SIPS, do we need more time to reflect on that choice? As the programming part could be relatively quick I think.

**Comment by psforscher** [comment]
very good points. i think you've convinced me that filtering is not appropriate. here is what i propose instead:

- in the top-bar, switch "General" and "All Fields"

<img width="1153" alt="Screenshot 2024-05-20 at 17 03 52" src="https://github.com/rempsyc/busara_dashboard/assets/149572347/7e017fa2-1a1b-4786-b7d1-662d9f52c73f">

- rename "General" to "General Interest" and "All Fields" to "All Behavioral Science"

this will clarify that "General" is really general-interest journals and is there as a comparison to behavioral science (the main focus of the dashboard)

**Comment by psforscher** [comment]
mm, i see you suggest eliminating "All Fields". i could see doing that, but i do want something that focuses on behavioral science specifically. i therefore lean toward keeping it but could be convinced that the graphs are just too hard to interpret

**Comment by rempsyc** [comment]
> i think you've convinced me that filtering is not appropriate.

Then I will close this issue for now. We can reopen later if we change our mind in the future.
