### ISSUE TITLE
Clipped citation on plots

### ISSUE THREAD

**Issue by psforscher** [rempsyc/busara_dashboard#50]
With the updated citation, the citation that is listed on the plots is now clipped at the edges; see below

<img width="867" alt="Screenshot 2024-07-24 at 11 38 58" src="https://github.com/user-attachments/assets/a6db8ff1-a0c7-4196-b316-f4cc6184f9d5">

**Comment by rempsyc** [comment]
good catch, and we can also the citation going overboard for the trend figure you linked on your other issue:

![newplot (5)](https://github.com/user-attachments/assets/80941305-6431-4f02-8ee4-5c73f95e7902)

I'm going to try to make the citation jump on 3 lines instead of 2 to fix that...

**Comment by psforscher** [comment]
i'm not seeing the citations anymore -- and actually, i think you may have accidentally reverted to an older version of the dashboard judging from the percentages shown in the dials

<img width="1440" alt="Screenshot 2024-07-24 at 18 40 59" src="https://github.com/user-attachments/assets/a125a734-a93f-47e3-ba04-458da97bd359">

**Comment by rempsyc** [comment]
Are you looking at https://remi-theriault.com/dashboards/busara instead of https://remi-theriault.com/dashboards/missing_majority? :P

**Comment by psforscher** [comment]
lol! thanks haha.

i'm just seeing a bit of overlap between citation and data in this plot. maybe the citation could be right-justified?
![newplot (8)](https://github.com/user-attachments/assets/92afd758-b720-4877-811b-a6b1e5d6ec9e)

looks good otherwise!

**Comment by psforscher** [comment]
ah ok. in the end i think it's not a huge deal! this just affects the one plot and the plot is perfectly interpretable

**Comment by rempsyc** [comment]
Was a bit complex to solve, but it is fixed now!
