### ISSUE TITLE
Consider making the color palette color blind friendly

### ISSUE THREAD

**Issue by rempsyc** [rempsyc/busara_dashboard#55]
The _Communications Psychology_ editor comments include the following:

> When choosing a color scheme please consider how it will display in black and white (if printed), and to users with color blindness. Please consider distinguishing data series using line patterns rather than colors, or using optimized color palettes such as those found at https://www.nature.com/articles/nmeth.1618. Please avoid the use of red/green color contrasts, as these may be difficult to interpret for colorblind readers.

This is also relevant given one X user's comment:

<img src="https://github.com/user-attachments/assets/6eb66ec8-3604-4253-a9a0-0680535d315a" width="60%">

Using line patterns can be interesting in certain cases when you have few categories, but in our cases of countries (hundreds), it can be impractical. Even though we only display a max of 8 categories per figure now, 8 line types can be visually overwhelming. It would also be possible to do it only for this publication with 6 line types for the continents, but I'm not sure.

So I'd think of considering a color blind friendly palette, but not line type. WDYT @psforscher?

**Comment by psforscher** [comment]
i'm definitely not a fan of patterned lines. it's easy to get accidental moire effects with patterned lines https://en.wikipedia.org/wiki/Moir%C3%A9_pattern

i'd vote for using something like the viridis colorset from [RColorBrewer](https://cran.r-project.org/web/packages/RColorBrewer/index.html). this has been my typical choice when making colorblind-friendly plots.

i also see that there's some nice guidance [here](https://cran.r-project.org/web/packages/colorBlindness/vignettes/colorBlindness.html) on colorblind-friendly choices in R. i don't know the packages mentioned aside from RColorBrewer, but i'm sure there's a decent option from among the listed resources.

**Comment by rempsyc** [comment]
Favorite palette? These are all from the Viridis colour scales from `viridisLite` and integrated in `ggplot2` by default

> magma

![image](https://github.com/user-attachments/assets/a7095ca1-4c6b-4c45-926d-87c909c4b78f)

> inferno

![image](https://github.com/user-attachments/assets/f2ad3a37-f04d-4149-a309-82679b780489)

> plasma

![image](https://github.com/user-attachments/assets/e2c52b75-d68f-4263-b2e1-d9da0090fb7f)

viridis
![image](https://github.com/user-attachments/assets/564c2f9b-b1d3-43e0-b625-6066b7510cce)

> cividis

![image](https://github.com/user-attachments/assets/e239dddf-f408-458e-baa4-5146a1abf76c)

> rocket

![image](https://github.com/user-attachments/assets/86fec515-f866-4854-9046-b96edb8a57a5)

> mako

![image](https://github.com/user-attachments/assets/68cf1a8c-787c-4df5-9480-a08dc17178ee)

> turbo

![image](https://github.com/user-attachments/assets/bcffc1ec-5640-422d-b9da-d98846522b82)

I don't like them as much as the default theme. However, it might just be because I'm not used to them. Anyway, accessibility is more important than aesthetics. Otherwise, viridis still your favorite? I like turbo too I think. 

Alternatives would include the following palettes from the `colorBlindness` package:

![image](https://github.com/user-attachments/assets/50b0698e-6ee5-4e68-bd1e-fb00486049bf)

**Comment by psforscher** [comment]
i like both viridis and turbo. maybe turbo? the colors feel quite distinct with that pallette

**Comment by rempsyc** [comment]
So our figure 1 would be:

![image](https://github.com/user-attachments/assets/178b855a-65bc-4dfc-acc4-7b743a43c483)

**Comment by rempsyc** [comment]
There is an additional difficulty in that the plot looks different whether it is generated as a dynamic plotly or a static image. The website shows the interactive plotly, which we can take a screenshot of, but it is low resolution. To export to PDF, it is only possible to export static, and so there will be differences with the website.

**Comment by rempsyc** [comment]
This is what Figure 2 looks like when saving directly from the plotly image export function. As I feared, it is pretty long... We could try repositioning panels to better use the space, but then it is not a "screenshot of the website" anymore and almost like "new data" I hope they're not going to be difficult about this.

![newplot](https://github.com/user-attachments/assets/bbe05535-4fec-45e9-9ee7-f6a4e291424f)

**Comment by rempsyc** [comment]
If we want to make it like a conventional figure, then, using 4 columns to try to make it fit to the letter format, we get... But to have a perfect 4 x 4, we could remove the journals that have poor data coverage like AMPPS and Collabra.

![Figure 2](https://github.com/user-attachments/assets/c86d3905-f892-47bb-8036-6b7eb06d8f80)

**Comment by psforscher** [comment]
i quite like the figure you past above with four panels across. it seems though that you think there's an issue with this figure that would require us to move some journals? i think it's fine as is ...

**Comment by rempsyc** [comment]
I thought it would make a more optimal use of space if we got rid of the white space empty panels (I had done the same for the old figure 2), but if you’re fine with that, alright let’s keep it as is.

**Comment by psforscher** [comment]
i think i'm fine with it!
