### ISSUE TITLE
Error merging old and new data

### ISSUE THREAD

**Issue by rempsyc** [rempsyc/busara_dashboard#56]
@psforscher we have another issue. I had temporarily deactivated downloading new data for our social media blitz to avoid things breaking down due to a bug or something of the sort. Given that the editor asked,

> Please ensure you update the dashboard to the latest version on the day of final manuscript submission.

I thought it would be more than time to reopen the download of fresh data. However, when I tried, I'm faced with a new bug. It seems like it is due to the data format on openAlex having changed. This means that I will need to redownload all the old data once again to make it compatible to the new, and probably change our processing functions, meaning it could involve a substantial amount of time to fix. Not sure if possible before the paper resubmission.

**Comment by psforscher** [comment]
oh no! well, if need be we can flag this to sakshi and she can see if the editor will be understanding. after all it's just a month or so of data -- not that much really

**Comment by rempsyc** [comment]
After many hours of effort, I was able to fix it and also added two journals to fill the space on the figure
